name: Deploy Website to Azure Blob

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload files to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name azureproject123 \
              --destination '$web' \
              --source . \
              --account-key "${{ secrets.AZURE_STORAGE_KEY }}"
